$(function() {
        $('.nav-about').on('click',function(event){
            event.preventDefault();
            $('.about-me').removeClass('hidden');
            $('.project-1').addClass('hidden');
            $('.project-2').addClass('hidden');
        });
        $('.nav-project-1').on('click',function(event){
            event.preventDefault();
            $('.project-1').removeClass('hidden');
            $('.about-me').addClass('hidden');
            $('.project-2').addClass('hidden');
        });
        $('.nav-project-2').on('click',function(event){
            event.preventDefault();
            $('.project-2').removeClass('hidden');
            $('.about-me').addClass('hidden');
            $('.project-1').addClass('hidden');
        });
    });